[package]
name = "rust_code"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
gifski = "1.34.0"
image = "0.25.8"
nalgebra = "0.34.1"
plotters = "0.3.7"
rand = "0.9.2"
serde = { version = "1.0.228", features = [ "derive" ] }
